apiVersion: v1
kind: Secret
metadata: 
  name: mongo-secret
  namespace: three-tier-app
type: Opaque
data:  
  password: RGV2b3BzLXByb2plY3QK   #Devops-project
  username: VGhyZWUtdGllci1hcHAK   #Three-tier-app