apiVersion: v1 
kind: Service
metadata:
  name: mongodb-svc
  namespace: three-tier-app
spec:
  selector:
    app: mongodb
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 27017        #Port on service
      targetPort: 27017  #Port on pod