apiVersion: v1 
kind: Service
metadata:
  name: api
  namespace: three-tier-app
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3500        #Port on service
      targetPort: 3500  #Port on pods 
