apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier-app
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - port: 3000    #Port on service 
    protocol: TCP         
    targetPort: 3000    #Port on pod.
    
 